services:
  consul:
    image: hashicorp/consul:1.22
    command: agent -dev -ui -client=0.0.0.0 -config-dir=/consul/config
    ports:
      - "8500:8500"
    volumes:
      - ./consul-config:/consul/config
    depends_on:
      - flight
      - hotel
      - car

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8084:8080"
    environment:
      URLS: >-
        [
          { "url": "http://localhost:8081/openapi", "name": "Flight Service" },
          { "url": "http://localhost:8082/openapi", "name": "Hotel Service" },
          { "url": "http://localhost:8083/openapi", "name": "Car Service" },
          { "url": "http://localhost:8085/openapi", "name": "Booking Service (Story 1)" },
          { "url": "http://localhost:8086/openapi", "name": "Booking Service (Story 2)" }
        ]
    depends_on:
      - flight
      - hotel
      - car
      - booking-story1