services:
  booking-story1:
    container_name: booking-story1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: booking/story1
    image: larmic/workshop-microservices-booking:story1
    ports:
      - "8085:8080"
    environment:
      FLIGHT_SERVICE_URL: http://flight:8080
      HOTEL_SERVICE_URL: http://hotel:8080
      CAR_SERVICE_URL: http://car:8080

  booking-story2:
    container_name: booking-story2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: booking/story2
    image: larmic/workshop-microservices-booking:story2
    ports:
      - "8086:8080"
    environment:
      CONSUL_URL: http://consul:8500
    depends_on:
      consul:
        condition: service_healthy

  booking-story3:
    container_name: booking-story3
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: booking/story3
    image: larmic/workshop-microservices-booking:story3
    ports:
      - "8087:8080"
    environment:
      CONSUL_URL: http://consul:8500
    depends_on:
      consul:
        condition: service_healthy

  booking-story4:
    container_name: booking-story4
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: booking/story4
    image: larmic/workshop-microservices-booking:story4
    ports:
      - "8088:8080"
    environment:
      CONSUL_URL: http://consul:8500
    depends_on:
      consul:
        condition: service_healthy

  booking-story5:
    container_name: booking-story5
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: booking/story5
    image: larmic/workshop-microservices-booking:story5
    ports:
      - "8089:8080"
    environment:
      CONSUL_URL: http://consul:8500
    depends_on:
      consul:
        condition: service_healthy

  booking-story6:
    container_name: booking-story6
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: booking/story6
    image: larmic/workshop-microservices-booking:story6
    ports:
      - "8090:8080"
    environment:
      CONSUL_URL: http://consul:8500
    depends_on:
      consul:
        condition: service_healthy

  booking-story7:
    container_name: booking-story7
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: booking/story7
    image: larmic/workshop-microservices-booking:story7
    ports:
      - "8091:8080"
    environment:
      CONSUL_URL: http://consul:8500
    depends_on:
      consul:
        condition: service_healthy