services:
  flight:
    build:
      context: .
      dockerfile: flight/Dockerfile
    image: larmic/workshop-microservices-flight:latest
    ports:
      - "8081:8080"

  hotel:
    build:
      context: .
      dockerfile: hotel/Dockerfile
    image: larmic/workshop-microservices-hotel:latest
    ports:
      - "8082:8080"

  car:
    build:
      context: .
      dockerfile: car/Dockerfile
    image: larmic/workshop-microservices-car:latest
    ports:
      - "8083:8080"

  booking-story1:
    build:
      context: .
      dockerfile: booking/story1/Dockerfile
    image: larmic/workshop-microservices-booking-story1:latest
    ports:
      - "8085:8080"
    environment:
      FLIGHT_SERVICE_URL: http://flight:8080
      HOTEL_SERVICE_URL: http://hotel:8080
      CAR_SERVICE_URL: http://car:8080
    depends_on:
      - flight
      - hotel
      - car

  booking-story2:
    build:
      context: .
      dockerfile: booking/story1/Dockerfile
    image: larmic/workshop-microservices-booking-story2:latest
    ports:
      - "8086:8080"
    environment:
      FLIGHT_SERVICE_URL: http://flight:8080
      HOTEL_SERVICE_URL: http://hotel:8080
      CAR_SERVICE_URL: http://car:8080
    depends_on:
      - flight
      - hotel
      - car
