services:
  flight:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: flight
    image: larmic/workshop-microservices-flight:latest
    ports:
      - "8081:8080"
    environment:
      CONSUL_URL: http://consul:8500
      SERVICE_NAME: flight-service
      SERVICE_ADDRESS: flight
    depends_on:
      - consul

  hotel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: hotel
    image: larmic/workshop-microservices-hotel:latest
    ports:
      - "8082:8080"
    environment:
      CONSUL_URL: http://consul:8500
      SERVICE_NAME: hotel-service
      SERVICE_ADDRESS: hotel
    depends_on:
      - consul

  car:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: car
    image: larmic/workshop-microservices-car:latest
    ports:
      - "8083:8080"
    environment:
      CONSUL_URL: http://consul:8500
      SERVICE_NAME: car-service
      SERVICE_ADDRESS: car
    depends_on:
      - consul
