http:
  routers:
    flight:
      rule: "PathPrefix(`/api/flight`)"
      entryPoints:
        - web
      middlewares:
        - flight-stripprefix
      service: flight

    hotel:
      rule: "PathPrefix(`/api/hotel`)"
      entryPoints:
        - web
      middlewares:
        - hotel-stripprefix
      service: hotel

    car:
      rule: "PathPrefix(`/api/car`)"
      entryPoints:
        - web
      middlewares:
        - car-stripprefix
      service: car

    booking-ref-story1:
      rule: "PathPrefix(`/api/booking-ref-story1`)"
      entryPoints:
        - web
      middlewares:
        - booking-ref-story1-stripprefix
      service: booking-ref-story1

    booking-ref-story2:
      rule: "PathPrefix(`/api/booking-ref-story2`)"
      entryPoints:
        - web
      middlewares:
        - booking-ref-story2-stripprefix
      service: booking-ref-story2

    booking-ref-story3:
      rule: "PathPrefix(`/api/booking-ref-story3`)"
      entryPoints:
        - web
      middlewares:
        - booking-ref-story3-stripprefix
      service: booking-ref-story3

    booking-ref-story4:
      rule: "PathPrefix(`/api/booking-ref-story4`)"
      entryPoints:
        - web
      middlewares:
        - booking-ref-story4-stripprefix
      service: booking-ref-story4

    booking-ref-story5:
      rule: "PathPrefix(`/api/booking-ref-story5`)"
      entryPoints:
        - web
      middlewares:
        - booking-ref-story5-stripprefix
      service: booking-ref-story5

    booking-ref-story6:
      rule: "PathPrefix(`/api/booking-ref-story6`)"
      entryPoints:
        - web
      middlewares:
        - booking-ref-story6-stripprefix
      service: booking-ref-story6

    booking-ref-story7:
      rule: "PathPrefix(`/api/booking-ref-story7`)"
      entryPoints:
        - web
      middlewares:
        - booking-ref-story7-stripprefix
      service: booking-ref-story7

    booking-custom:
      rule: "PathPrefix(`/api/booking-custom`)"
      entryPoints:
        - web
      middlewares:
        - booking-custom-stripprefix
      service: booking-custom

    root:
      rule: "Path(`/`)"
      entryPoints:
        - web
      service: dashboard

    dashboard:
      rule: "PathPrefix(`/dashboard`)"
      entryPoints:
        - web
      middlewares:
        - dashboard-stripprefix
      service: dashboard

    swagger-ui:
      rule: "PathPrefix(`/api`)"
      entryPoints:
        - web
      service: swagger-ui

    consul:
      rule: "PathPrefix(`/consul`)"
      entryPoints:
        - web
      service: consul

    consul-api:
      rule: "PathPrefix(`/v1`)"
      entryPoints:
        - web
      service: consul

    slides:
      rule: "PathPrefix(`/slides`)"
      entryPoints:
        - web
      middlewares:
        - slides-stripprefix
      service: slides

  middlewares:
    flight-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/flight"

    hotel-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/hotel"

    car-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/car"

    booking-ref-story1-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/booking-ref-story1"

    booking-ref-story2-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/booking-ref-story2"

    booking-ref-story3-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/booking-ref-story3"

    booking-ref-story4-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/booking-ref-story4"

    booking-ref-story5-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/booking-ref-story5"

    booking-ref-story6-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/booking-ref-story6"

    booking-ref-story7-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/booking-ref-story7"

    booking-custom-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/booking-custom"

    dashboard-stripprefix:
      stripPrefix:
        prefixes:
          - "/dashboard"

    slides-stripprefix:
      stripPrefix:
        prefixes:
          - "/slides"

  services:
    flight:
      loadBalancer:
        servers:
          - url: "http://flight:8080"

    hotel:
      loadBalancer:
        servers:
          - url: "http://hotel:8080"

    car:
      loadBalancer:
        servers:
          - url: "http://car:8080"

    booking-ref-story1:
      loadBalancer:
        servers:
          - url: "http://booking-ref-story1:8080"

    booking-ref-story2:
      loadBalancer:
        servers:
          - url: "http://booking-ref-story2:8080"

    booking-ref-story3:
      loadBalancer:
        servers:
          - url: "http://booking-ref-story3:8080"

    booking-ref-story4:
      loadBalancer:
        servers:
          - url: "http://booking-ref-story4:8080"

    booking-ref-story5:
      loadBalancer:
        servers:
          - url: "http://booking-ref-story5:8080"

    booking-ref-story6:
      loadBalancer:
        servers:
          - url: "http://booking-ref-story6:8080"

    booking-ref-story7:
      loadBalancer:
        servers:
          - url: "http://booking-ref-story7:8080"

    booking-custom:
      loadBalancer:
        servers:
          - url: "http://booking-custom:8080"

    dashboard:
      loadBalancer:
        servers:
          - url: "http://dashboard:8080"

    swagger-ui:
      loadBalancer:
        servers:
          - url: "http://swagger-ui:8080"

    consul:
      loadBalancer:
        servers:
          - url: "http://consul:8500"

    slides:
      loadBalancer:
        servers:
          - url: "http://slides:80"
